{
    "data": {
        "entries": [
            {
                "connection_class": "local_push",
                "data": {
                    "broker": "192.168.100.243",
                    "discovery": true,
                    "password": "Lotus1994",
                    "port": 1883,
                    "username": "Marius"
                },
                "domain": "mqtt",
                "entry_id": "2bfd5cb593214e1a9e4519d90b4682d4",
                "options": {},
                "source": "user",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "192.168.100.243",
                "version": 1
            },
            {
                "connection_class": "local_push",
                "data": {
                    "host": "192.168.100.23",
                    "password": "",
                    "port": 6053
                },
                "domain": "esphome",
                "entry_id": "a32abd2aa8964d5d8d100359f39883bd",
                "options": {},
                "source": "discovery",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "esphometest1",
                "version": 1
            },
            {
                "connection_class": "local_push",
                "data": {
                    "host": "wood_lamp.local",
                    "password": "",
                    "port": 6053
                },
                "domain": "esphome",
                "entry_id": "7188c338301347d1a023f8340e19bd59",
                "options": {},
                "source": "discovery",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "wood_lamp",
                "version": 1
            },
            {
                "connection_class": "cloud_push",
                "data": {
                    "app_data": {
                        "push_token": "cI51t1eobB8:APA91bHY4MeyBYBwKsdHOl6pa5T9wgTs3Zuq__wG3yPDNcavHM12RpJT4AS-sMDhOZxVpnv4frNWAQLVG-X1y56qWDnsvyq9e_yvV5wKjL7-JuFA7PT-UH64rsrZxbTRhu6QWxsi2ptQ",
                        "push_url": "https://us-central1-ha-client-c73c4.cloudfunctions.net/sendPushNotification"
                    },
                    "app_id": "ha_client",
                    "app_name": "HA Client",
                    "app_version": "0.7.7",
                    "cloudhook_url": "https://hooks.nabu.casa/gAAAAABd0syb3kry1Q9YreCkmuSbq0mH7lTOWmaJlW3VTTPqrTL_11mfap9868MyNLbcwW6cHmSOEfroJbITaF6_1INLwsqt_QTTI2iXPjiQk__2IcNfUN17VcTgWIWYaGquyGb1Es9T0C7cIveXvbXdj003epYXCMdg_ZDix5ycqgFfrA4cb7c=",
                    "device_id": "f4a1a13bd946478eaee33decf5ee60a8",
                    "device_name": "Ungurean Marius's SM-A505FN",
                    "manufacturer": "samsung",
                    "model": "SM-A505FN",
                    "os_name": "Android",
                    "os_version": "9",
                    "supports_encryption": false,
                    "user_id": "223c149ebdde4893ad6e376a47668977",
                    "webhook_id": "cb4b48ca302550bf06b5fe7c1ac1e90e29e6180f3749aae6780a03086c7d0f3c"
                },
                "domain": "mobile_app",
                "entry_id": "571ace18bdc44f3b954b8f2bd77f1c9a",
                "options": {},
                "source": "registration",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "Ungurean Marius's SM-A505FN",
                "version": 1
            },
            {
                "connection_class": "cloud_push",
                "data": {
                    "app_data": {
                        "push_token": "cTgVEb8pakA:APA91bEqSy3DvL8G-tJcvIFbLpeVVcS4e1jcaRG9peTlwPI26qa7TMdTqmfS_GPLR1ms_LUlb-aTIWvkYAlrp37Wyipe6899y3j7GzTetYsBzqDipNXXbe_FyrLSeQLtgyDiZzZzEvF8",
                        "push_url": "https://ariela.surodev.com/notification/"
                    },
                    "app_id": "com.surodev.ariela",
                    "app_name": "Ariela",
                    "app_version": "1.3.8.1",
                    "cloudhook_url": "https://hooks.nabu.casa/gAAAAABd2tygienxb3sLG-IvSGHDLXkUkkhNQl-6BYEwmyq6VkxJqpi9-XmbySGxU4DqQ5_bErpUwUP3nsKUo0SpDodlEgqX017xxauqh7Dz5gVSLdKVxiHlGo7JH1cWNQiSVe7Z4zQxF5LulGTQM6m8qTJuDelUghpGe_0vXkCMbq7GQtYpzsM=",
                    "device_id": "c240a512744c4b3aa444823a22e5f25f",
                    "device_name": "Marius's_phone",
                    "manufacturer": "samsung",
                    "model": "a50",
                    "os_name": "9",
                    "os_version": "9",
                    "supports_encryption": false,
                    "user_id": "223c149ebdde4893ad6e376a47668977",
                    "webhook_id": "c99408fc5dc8c4d38342c8acb4a3a646fcabc98aae5748508589be11915012fe"
                },
                "domain": "mobile_app",
                "entry_id": "f456a6602d5c44f5a84c44764c9f7ea5",
                "options": {},
                "source": "registration",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "Marius's_phone",
                "version": 1
            }
        ]
    },
    "key": "core.config_entries",
    "version": 1
}